/*
 * Copyright (C) 2018-2026 Modding Craft ZBD Studio.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

-- 队伍信息表
create table if not exists dj_team
(
    exam_number varchar(50) not null primary key,
    team_name   varchar(50) not null,
    school      varchar(50) not null,
    position    varchar(50) not null,
    account     varchar(50) not null,
    password    varchar(50) not null,
    teammate   varchar(100) not null,
    coach       varchar(50),
    constraint position unique (position)
    );
comment on table dj_team is '存放Domjudge队伍信息的表';

-- 登录任务表
create table if not exists auth_task
(
    exam_num      varchar(50) not null,
    old_client_id varchar(50) not null,
    now_client_id varchar(50) not null,
    id            bigint generated by default as identity primary key,
    create_time   timestamp    not null, -- 修复：DATETIME → TIMESTAMP
    status        varchar(50) not null,
    constraint exam_num foreign key (exam_num) references dj_team (exam_number)
    );
comment on table auth_task is '登录请求队列';

-- 打印任务表
create table if not exists print_task
(
    id          bigint generated by default as identity primary key,
    create_time timestamp     not null, -- 修复：DATETIME → TIMESTAMP
    status      varchar(50)  not null,
    exam_num    varchar(50)  not null,
    file_path   varchar(100) not null,
    file_name   varchar(50) not null,
    constraint team_num foreign key (exam_num) references dj_team (exam_number)
    );
comment on table print_task is '打印请求队列';

-- 队伍客户端表
create table if not exists team_client
(
    exam_num   varchar(50) not null primary key,
    client_id  varchar(50) not null,
    login_time timestamp    not null, -- 修复：DATETIME → TIMESTAMP
    constraint exam_number foreign key (exam_num) references dj_team (exam_number)
    );
comment on table team_client is '查询队伍登录客户端ID的表';